# IntelliFlow AI Platform - Kubernetes Secrets Template
# This file shows the structure of secrets needed. 
# In production, use Vault or external secret management.

apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  DB_USERNAME: cG9zdGdyZXM=  # postgres
  DB_PASSWORD: cGFzc3dvcmQ=  # password - CHANGE THIS
  DB_HOST: cG9zdGdyZXM=      # postgres
  DB_PORT: NTQzMg==          # 5432

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  REDIS_PASSWORD: cmVkaXMxMjM=  # redis123 - CHANGE THIS
  REDIS_HOST: cmVkaXM=          # redis
  REDIS_PORT: NjM3OQ==          # 6379

---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  MONGO_USERNAME: YWRtaW4=    # admin
  MONGO_PASSWORD: YWRtaW4xMjM= # admin123 - CHANGE THIS
  MONGO_HOST: bW9uZ29kYg==     # mongodb
  MONGO_PORT: MjcwMTc=        # 27017

---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  # Generate strong JWT secret with: openssl rand -base64 32
  JWT_SECRET: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb24xMjM0NTY3ODk=
  JWT_EXPIRATION: ODY0MDAwMDA=      # 86400000 (24 hours)
  JWT_REFRESH_EXPIRATION: NjA0ODAwMDAw # 604800000 (7 days)

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  KAFKA_BOOTSTRAP_SERVERS: a2Fma2E6OTA5Mg== # kafka:9092
  KAFKA_USERNAME: a2Fma2E=                  # kafka (if SASL enabled)
  KAFKA_PASSWORD: a2Fma2EtcGFzc3dvcmQ=      # kafka-password (if SASL enabled)

---
apiVersion: v1
kind: Secret
metadata:
  name: notification-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  SMTP_HOST: c210cC5nbWFpbC5jb20=    # smtp.gmail.com
  SMTP_PORT: NTg3                   # 587
  SMTP_USERNAME: bm90aWZpY2F0aW9uc0BpbnRlbGxpZmxvdy5jb20= # notifications@intelliflow.com
  SMTP_PASSWORD: eW91ci1lbWFpbC1wYXNzd29yZA==             # your-email-password - CHANGE THIS
  SLACK_WEBHOOK_URL: aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVE9ET19BRER9  # TODO: ADD REAL WEBHOOK

---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQUlPU0ZPRE5ON0VYQU1QTEU=     # AKIAIOSFODNN7EXAMPLE - CHANGE THIS
  AWS_SECRET_ACCESS_KEY: d0phbFJYVXRuRkVNSS9LN01ERU5HL2JQeFJmaUNZRVhBTVBMRUtFWQ== # wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY - CHANGE THIS
  AWS_REGION: dXMtd2VzdC0y                           # us-west-2
  S3_BUCKET_NAME: aW50ZWxsaWZsb3ctbW9kZWxz            # intelliflow-models

---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  MLFLOW_TRACKING_URI: aHR0cDovL21sZmxvdy5pbnRlbGxpZmxvdy5jb20= # http://mlflow.intelliflow.com
  MLFLOW_S3_ENDPOINT_URL: aHR0cHM6Ly9zMy51cy13ZXN0LTIuYW1hem9uYXdzLmNvbQ== # https://s3.us-west-2.amazonaws.com
  MLFLOW_TRACKING_USERNAME: bWxmbG93              # mlflow
  MLFLOW_TRACKING_PASSWORD: bWxmbG93LXBhc3N3b3Jk  # mlflow-password - CHANGE THIS

---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  VAULT_ADDR: aHR0cHM6Ly92YXVsdC5pbnRlbGxpZmxvdy5jb20=  # https://vault.intelliflow.com
  VAULT_TOKEN: aHZ2cy4uLg==                          # hvvs... - CHANGE THIS
  VAULT_NAMESPACE: aW50ZWxsaWZsb3c=                  # intelliflow

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: intelliflow-prod
type: Opaque
data:
  GRAFANA_API_KEY: ZXlKaGJHY2lPaUpTVXpJMU5pSjk=      # Grafana API key - CHANGE THIS
  PROMETHEUS_API_TOKEN: cHJvbS10b2tlbi0xMjM=        # prom-token-123 - CHANGE THIS