apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: database
type: Opaque
stringData:
  DB_USERNAME: intelliflow_user
  DB_PASSWORD: SecureDBPassword123!
  POSTGRES_PASSWORD: PostgresAdminPass456!
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: redis
type: Opaque
stringData:
  REDIS_PASSWORD: RedisSecurePass789!
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: auth
type: Opaque
stringData:
  JWT_SECRET: MyVerySecureJWTSigningKey2024!@#$%^&*()
---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: kafka
type: Opaque
stringData:
  KAFKA_USERNAME: kafka_user
  KAFKA_PASSWORD: KafkaSecurePass321!
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: vault
type: Opaque
stringData:
  VAULT_TOKEN: hvs.secretvaulttoken12345
  VAULT_ADDR: http://vault-service:8200
---
apiVersion: v1
kind: Secret
metadata:
  name: mlflow-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: mlflow
type: Opaque
stringData:
  MLFLOW_TRACKING_USERNAME: mlflow_admin
  MLFLOW_TRACKING_PASSWORD: MLflowSecure987!
  AWS_ACCESS_KEY_ID: AKIAIOSFODNN7EXAMPLE
  AWS_SECRET_ACCESS_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
---
apiVersion: v1
kind: Secret
metadata:
  name: smtp-secrets
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: notification
type: Opaque
stringData:
  SMTP_USERNAME: noreply@intelliflow.com
  SMTP_PASSWORD: SMTPSecurePass654!
  SMTP_HOST: smtp.gmail.com
  SMTP_PORT: "587"
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: intelliflow-monitoring
  labels:
    app: intelliflow
    component: monitoring
type: Opaque
stringData:
  GRAFANA_ADMIN_PASSWORD: GrafanaSecure123!
  PROMETHEUS_PASSWORD: PrometheusSecure456!
  ELASTICSEARCH_PASSWORD: ElasticSecure789!
---
apiVersion: v1
kind: Secret
metadata:
  name: tls-certificates
  namespace: intelliflow-prod
  labels:
    app: intelliflow
    component: tls
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t    # Base64 encoded private key
