apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: intelliflow-prod
  labels:
    app: user-service
    component: config
    version: v1.0.0
data:
  application.yml: |
    server:
      port: 8080
      servlet:
        context-path: /api/v1
    
    spring:
      application:
        name: user-service
      
      datasource:
        url: jdbc:postgresql://postgres-service:5432/intelliflow_users
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 20
          minimum-idle: 5
          connection-timeout: 30000
          idle-timeout: 600000
          max-lifetime: 1800000
      
      jpa:
        hibernate:
          ddl-auto: validate
        show-sql: false
        properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            format_sql: true
      
      flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
      
      redis:
        host: redis-service
        port: 6379
        password: ${REDIS_PASSWORD}
        database: 0
        timeout: 2000ms
        lettuce:
          pool:
            max-active: 20
            max-idle: 10
            min-idle: 5
      
      kafka:
        bootstrap-servers: kafka-service:9092
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
          acks: all
          retries: 3
          batch-size: 16384
          linger-ms: 5
        consumer:
          group-id: user-service-group
          auto-offset-reset: earliest
          key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
          value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
          properties:
            spring.json.trusted.packages: "com.intelliflow.shared.messaging"
    
    eureka:
      client:
        service-url:
          defaultZone: http://eureka-service:8761/eureka/
        register-with-eureka: true
        fetch-registry: true
      instance:
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 10
        lease-expiration-duration-in-seconds: 30
    
    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
          base-path: /actuator
      endpoint:
        health:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true
      metrics:
        export:
          prometheus:
            enabled: true
    
    logging:
      level:
        com.intelliflow: INFO
        org.springframework.security: DEBUG
        org.springframework.web: INFO
      pattern:
        console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level [%X{correlationId}] %logger{36} - %msg%n"
      
    jwt:
      secret: ${JWT_SECRET}
      expiration: 86400000
      refresh-expiration: 604800000
    
    app:
      cors:
        allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
        allowed-methods: GET,POST,PUT,DELETE,OPTIONS
        allowed-headers: "*"
        allow-credentials: true
      
      rate-limiting:
        enabled: true
        requests-per-minute: 100
        burst-capacity: 200
      
      security:
        password-strength:
          min-length: 8
          require-uppercase: true
          require-lowercase: true
          require-numbers: true
          require-special-chars: true
        
        account-lockout:
          max-failed-attempts: 5
          lockout-duration-minutes: 30
        
        session:
          timeout-minutes: 30
          max-concurrent-sessions: 3
