apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: intelliflow-prod
  labels:
    app: user-service
    component: microservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: user-service
---
apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: intelliflow-prod
  labels:
    app: transaction-service
    component: microservice
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: transaction-service
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection-service
  namespace: intelliflow-prod
  labels:
    app: fraud-detection-service
    component: ml-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  - name: grpc
    port: 9000
    targetPort: 9000
    protocol: TCP
  - name: monitor
    port: 8001
    targetPort: 8001
    protocol: TCP
  selector:
    app: fraud-detection-service
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: intelliflow-prod
  labels:
    app: analytics-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: analytics-service
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: intelliflow-prod
  labels:
    app: notification-service
    component: microservice
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: actuator
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: notification-service
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: intelliflow-prod
  labels:
    app: api-gateway
    component: gateway
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-2:123456789012:certificate/12345678-1234-1234-1234-123456789012
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  selector:
    app: api-gateway
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: intelliflow-prod
  labels:
    app: postgres
    component: database
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: intelliflow-prod
  labels:
    app: redis
    component: cache
spec:
  type: ClusterIP
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: intelliflow-prod
  labels:
    app: kafka
    component: messaging
spec:
  type: ClusterIP
  ports:
  - name: kafka
    port: 9092
    targetPort: 9092
    protocol: TCP
  - name: kafka-ui
    port: 9093
    targetPort: 9093
    protocol: TCP
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
  namespace: intelliflow-prod
  labels:
    app: eureka
    component: discovery
spec:
  type: ClusterIP
  ports:
  - name: eureka
    port: 8761
    targetPort: 8761
    protocol: TCP
  selector:
    app: eureka
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  namespace: intelliflow-prod
  labels:
    app: mlflow
    component: ml-platform
spec:
  type: ClusterIP
  ports:
  - name: mlflow
    port: 5000
    targetPort: 5000
    protocol: TCP
  selector:
    app: mlflow
---
apiVersion: v1
kind: Service
metadata:
  name: ai-orchestrator-service
  namespace: intelliflow-prod
  labels:
    app: ai-orchestrator
    component: ml-platform
spec:
  type: ClusterIP
  ports:
  - name: management
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: monitoring
    port: 8081
    targetPort: 8081
    protocol: TCP
  selector:
    app: ai-orchestrator
